# Generated by Django 2.1.7 on 2019-03-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='distance',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
