# Generated by Django 2.1.7 on 2019-03-05 16:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourx', '0002_userextra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExtra',
            new_name='Profile',
        ),
    ]
