# Generated by Django 2.1.7 on 2019-03-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourx', '0005_auto_20190327_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='price',
            field=models.CharField(default=100, max_length=10),
            preserve_default=False,
        ),
    ]
