# Generated by Django 2.1.7 on 2019-03-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourx', '0005_auto_20190305_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_scout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(default='12/12/2010'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
    ]
