# Generated by Django 2.1.7 on 2019-03-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourx', '0007_auto_20190305_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(default='2010-12-30'),
        ),
    ]
