# Generated by Django 2.1.7 on 2019-03-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourx', '0008_auto_20190305_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
    ]
