# Generated by Django 2.1.7 on 2019-03-06 01:19

from django.db import migrations, models
import tourx.models


class Migration(migrations.Migration):

    dependencies = [
        ('tourx', '0010_auto_20190306_0029'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', tourx.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
