# Generated by Django 2.1.7 on 2019-03-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourx', '0011_auto_20190306_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profile Picture'),
        ),
    ]
